apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "detect-suspicious-shell-from-nginx"
spec:
  kprobes:
  - call: "sys_execve"
    syscall: true
    args:
    - index: 0
      type: "string"
    selectors:
    - matchPIDs:
      - operator: In
        values: [33] # Strict filtering based on the www-data UID
      matchArgs:      
      - index: 0
        operator: "Equal"
        values:
        - "/bin/sh"
        - "/bin/bash"